print("Nama\t\t\t: Ruel Misquerable")
print("NIM\t\t\t: A14.2020.22221")
print("Tempat/Tanggal Lahir\t: Indonesia, 23 September 1993")
print("Email Mahasiswa \t: 111420202221@mhs.dinus.ac.id")
print("Email Umum\t\t: ruel.misquerable@gmail.com")
print("No HP\t\t\t: 08887392822")
print("Alamat\t\t\t: Broker Street Line 20 No. 15")
print("Agama\t\t\t: Islam")
print("Warga Negara\t\t: Australian")
print("Status Pekerjaan\t: Mahasiswa")
print("Dosen Wali\t\t: Xavierus Baltazar.PhD")